package com.softdesign.devintensive.data.storage.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USERS".
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "USERS";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property RemoteId = new Property(0, String.class, "remoteId", true, "REMOTE_ID");
        public final static Property Photo = new Property(1, String.class, "photo", false, "PHOTO");
        public final static Property FullName = new Property(2, String.class, "fullName", false, "FULL_NAME");
        public final static Property SearchName = new Property(3, String.class, "searchName", false, "SEARCH_NAME");
        public final static Property Rating = new Property(4, int.class, "rating", false, "RATING");
        public final static Property CodeLines = new Property(5, int.class, "codeLines", false, "CODE_LINES");
        public final static Property Projects = new Property(6, int.class, "projects", false, "PROJECTS");
        public final static Property Bio = new Property(7, String.class, "bio", false, "BIO");
    };

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USERS\" (" + //
                "\"REMOTE_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: remoteId
                "\"PHOTO\" TEXT," + // 1: photo
                "\"FULL_NAME\" TEXT NOT NULL UNIQUE ," + // 2: fullName
                "\"SEARCH_NAME\" TEXT NOT NULL UNIQUE ," + // 3: searchName
                "\"RATING\" INTEGER NOT NULL ," + // 4: rating
                "\"CODE_LINES\" INTEGER NOT NULL ," + // 5: codeLines
                "\"PROJECTS\" INTEGER NOT NULL ," + // 6: projects
                "\"BIO\" TEXT);"); // 7: bio
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        String remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindString(1, remoteId);
        }
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(2, photo);
        }
        stmt.bindString(3, entity.getFullName());
        stmt.bindString(4, entity.getSearchName());
        stmt.bindLong(5, entity.getRating());
        stmt.bindLong(6, entity.getCodeLines());
        stmt.bindLong(7, entity.getProjects());
 
        String bio = entity.getBio();
        if (bio != null) {
            stmt.bindString(8, bio);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        String remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindString(1, remoteId);
        }
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(2, photo);
        }
        stmt.bindString(3, entity.getFullName());
        stmt.bindString(4, entity.getSearchName());
        stmt.bindLong(5, entity.getRating());
        stmt.bindLong(6, entity.getCodeLines());
        stmt.bindLong(7, entity.getProjects());
 
        String bio = entity.getBio();
        if (bio != null) {
            stmt.bindString(8, bio);
        }
    }

    @Override
    protected final void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // remoteId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // photo
            cursor.getString(offset + 2), // fullName
            cursor.getString(offset + 3), // searchName
            cursor.getInt(offset + 4), // rating
            cursor.getInt(offset + 5), // codeLines
            cursor.getInt(offset + 6), // projects
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // bio
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setRemoteId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPhoto(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFullName(cursor.getString(offset + 2));
        entity.setSearchName(cursor.getString(offset + 3));
        entity.setRating(cursor.getInt(offset + 4));
        entity.setCodeLines(cursor.getInt(offset + 5));
        entity.setProjects(cursor.getInt(offset + 6));
        entity.setBio(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getRemoteId();
    }
    
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getRemoteId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
